In [14]:
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])
#print shape
print ("shape of the data: ", data.shape)

#mean temp per station
mean_temp_station = np.mean(data, axis=1)
print ("mean temp per station: ", mean_temp_station)

shape of the data:  (4, 5)
mean temp per station:  [25.3  23.78 26.58 25.26]


In [15]:
#boolean mask
mask = data > 28.0

#extract all temp >28.0
temp_above_28= data [mask]

print ("temp above 28.0°C: ", temp_above_28)

temp above 28.0°C:  [31.2 28.7 30.5 33.1 29.6 31.9 28.1]


In [16]:
# normalize the range (0,1)
normalized = (data - data.min()) / (data.max() - data.min())

# rounded to 2 deci places:
normalized_rounded = np.round(normalized, 2)

print(normalized_rounded)

[[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
